openapi: 3.0.3
servers:
  - url: https://qa-pxp-cagetransactions-api.azurewebsites.net/api/v1
info:
  description: >-
    This is an API reference for all internal Unity services
  version: 1.0.0
  title: Unity (Internal Services)
  contact:
    email: salvatore.cicero@pxpfinancial.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /vouchers: 
    post:
      summary: Create a Cage Voucher
      operationId: createVoucher
      tags:
        - Cage Transactions   
      requestBody:
        description: Create a Cage Voucher
        required: true      
        content:
          application/json:
            schema:
              type: object
              properties:
                site:
                  $ref: "#/components/schemas/site"
                voucherNumber:
                  $ref: "#/components/schemas/voucherNumber"
                amount:
                  $ref: "#/components/schemas/amount"               
                currency:
                  $ref: "#/components/schemas/currency"
                shopper:
                  $ref: "#/components/schemas/shopper"
      responses:
        200:
          description: Voucher Created
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/createVoucherResponse"               
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        400:
          description: Invalid Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - code
                  - reason
                properties:   
                  code:
                    type: string                
                    example: "INVALID_REQUEST"
                  reason:
                    type: string                
                    example: "One or more validation errors occurred"
                  details:
                    type: array
                    items: {}
                    example: "['$.voucherNumber' - The voucherNumber field is required]"                    
    get:
      summary: Get Cage Voucher
      operationId: getVoucher
      tags:
        - Cage Transactions
      parameters:
        - name: site
          in: query
          description: The unique site identifier, with which you want to process the transaction. This can be for example a store, hotel, a website etc. This value is generated by PXP Financial
          required: true
          schema:
            type: string
            maxLength: 20
            example: "SITE-001"
        - name: voucherNumber
          in: query
          description: This is the voucher number required by the shopper to make a withdrawal
          required: true
          schema:
            type: string
            maxLength: 50
            example: "1234567890"
      responses:
        200:
          description: State of Voucher
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/voucherResponse"
              examples: 
                  Voucher Created:
                    value: 
                      voucherNumber: "1234567890"
                      state: "VoucherCreated"
                      stateMessage: "Voucher Created"
                      amount: 30.33
                      currency: USD
                      shopper:
                        id: "shopper_01"
                        firstName: "John"
                        lastName: "Doe"
                        dateOfBirth: "1982-07-12"
                        email: "john.doe@pxpfinancial.com"
                  Voucher Paid:
                    value: 
                      voucherNumber: "1234567890"
                      state: "VoucherPaid"
                      stateMessage: "Voucher Paid"
                      amount: 30.33
                      currency: USD
                      paymentTypeAmounts:
                        cash: 10.2
                        cheque: 20.1
                        chips: 0
                        other: 0
                      shopper:
                        id: "shopper_01"
                        firstName: "John"
                        lastName: "Doe"
                        dateOfBirth: "1982-07-12"
                        email: "john.doe@pxpfinancial.com"
                  Voucher Expired:
                    value: 
                      voucherNumber: "1234567890"
                      state: "VoucherExpired"                   
                      stateMessage: "Voucher Expired"
                      amount: 30.33
                      currency: USD
                      shopper:
                        id: "shopper_01"
                        firstName: "John"
                        lastName: "Doe"
                        dateOfBirth: "1982-07-12"
                        email: "john.doe@pxpfinancial.com"                    
  /deposits:  
    post:
      summary: Create a Cage Deposit
      operationId: createDeposit
      tags:
        - Cage Transactions
      requestBody:
        description: Create a Cage Deposit
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                site:
                  $ref: "#/components/schemas/site"
                amount:
                  $ref: "#/components/schemas/amount"
                currency:
                  $ref: "#/components/schemas/currency"
                shopper:
                  $ref: "#/components/schemas/shopperId"
                paymentTypeAmounts:
                  $ref: "#/components/schemas/paymentTypeAmounts"
      responses:
        200:
          description: Cage Deposit Approved
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/transactionResponse"                  
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        400:
          description: Invalid Request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  code:
                    type: string                
                    example: "INVALID_REQUEST"
                  reason:
                    type: string                
                    example: "One or more validation errors occurred"
                  details:
                    type: array
                    items: {}
                    example: "['$.voucherNumber' - The voucherNumber field is required]"                           
  /withdrawals:
    post:
      summary: Create a Cage Withdrawal
      operationId: createWithdrawal
      tags:
        - Cage Transactions
      requestBody:
        description: Create a Cage Withdrawal
        required: true
        content:
          application/json:
            schema:
              type: object 
              properties:
                site:
                  $ref: "#/components/schemas/site"
                voucherNumber:
                  $ref: "#/components/schemas/voucherNumber"
                paymentTypeAmounts:
                  $ref: "#/components/schemas/paymentTypeAmounts"
      responses:
        200:
          description: Cage Withdrawal Approved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transactionResponse"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        400:
          description: Invalid Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - code
                  - reason                 
                properties: 
                  code:
                    type: string                
                    example: "INVALID_REQUEST"
                  reason:
                    type: string                
                    example: "One or more validation errors occurred"
                  details:
                    type: array
                    items: {}
                    example: "['$.voucherNumber' - The voucherNumber field is required]"                    
  /merchants:
    servers:
      - url: https://qa-pxp-onboarding-api.azurewebsites.net/api/v1
    get:
      summary: List all merchants
      operationId: listMerchants
      tags:
        - Merchant Setup
      parameters:
        - name: partner
          in: query
          description: The unique partner identifier, with which you want to process the transaction. This value is generated by PXP Financial
          required: true
          schema:
            type: string
            maxLength: 20
            example: "PART-0001"
      responses:
        200:
          description: An array of merchants
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/merchant"   
  /sites:
    servers:
      - url: https://qa-pxp-onboarding-api.azurewebsites.net/api/v1
    get:
      summary: List all sites
      operationId: listSites
      tags:
        - Merchant Setup
      parameters:
        - name: partner
          in: query
          description: The unique partner identifier, with which you want to process the transaction. This value is generated by PXP Financial
          required: true
          schema:
            type: string
            maxLength: 20
            example: "PARTNER_ACCOUNT_1"
        - name: merchant
          in: query
          description: The unique merchant identifier, with which you want to process the transaction. This value is generated by PXP Financial
          required: true
          schema:
            type: string
            maxLength: 20
            example: "MERCHANT_ACCOUNT_1"            
      responses:
        200:
          description: An array of merchants
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: "#/components/schemas/merchants"
  /currencies:
    servers:
      - url: https://qa-pxp-systemsetup-api.azurewebsites.net/api/v1
    get:
      summary: List all currencies
      operationId: listCurrencies
      tags:
        - System Setup
      parameters:
        - name: currencyCode
          in: query
          description: The ISO Currency Code
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 3
            example: "GBP"
      responses:
        200:
          description: An array of currencies
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: "#/components/schemas/currencies"
components:
  schemas:
    site:
      required: 
        - site
      type: string
      description: The unique site identifier, with which you want to process the transaction. This can be for example a store, hotel, a website etc. This value is generated by PXP Financial
      example: "SITE-0001"
      maximum: 20
    voucherNumber:    
      required: 
        - voucherNumber    
      type: string
      description: This is the voucher number required by the shopper to make a withdrawal
      maximum: 50
      example: "1234567890"
    amount:
      type: number
      required:
        - amount
      description: This is the amount of the transaction.  The numbers after the decimal will be zero padded if they are less than the expected currency exponent i.e. GBP 1.1 = GBP 1.10 OR EUR 1 = EUR 1.00 OR BHD 1.3 = 1.300  The transaction will be rejected if numbers after the decimal are greater than the expected currency exponent i.e. GBP 1.234 OR if a decimal is supplied when the currency of exponent does not require it i.e. JPY 1.0
      example: 30.33
    currency:
      type: string
      required: 
        - currency
      description: This is the currency of the transaction. This is the currency code. A three character code in accordance with ISO 4217
      minimum: 3
      maximum: 3
      example: "EUR"  
    shopperId:
      type: object 
      required:
        - id
      properties:
        id:
          type: string
          pattern: '^[A-Za-z0-9 _-]'
          example: "Shopper_01"
          maximum: 50      
          description: This is the unique identifier of the shopper
    error:
      required:
        - code
        - reason
      properties:
        code:
          type: string
        reason:
          type: string
        details:
          type: array  
          items: {}  
    paymentTypeAmounts:
      description: "This is a collection of payment types used that equal the amount for a cage deposit or withdrawal"
      required:
        - cash
        - chip
        - cheque
        - other
      properties:
        cash:
          type: number
          example: 10.11
          description: "This is the total amount in cash in order to make a Cage deposit or withdrawal"
        chip:
          type: number
          example: 10.11
          description: "This is the total amount in chips in order to make a Cage deposit or withdrawal"
        cheque:
          type: number
          example: 10.11
          description: "This is the total amount in cheques in order to make a Cage deposit or withdrawal"
        other: 
          type: number
          example: 0
          description: "This is the total amount other than cash, chips or cheques in order to make a Cage deposit or withdrawal"
    shopper:
      description: "This is the details of the shopper"
      required:
        - id
        - firstName
        - lastName
        - dateOfBirth
        - email
      properties:
        id:
          type: string
          pattern: '^[A-Za-z0-9 _-]'
          example: "Shopper_01"
          maximum: 50      
          description: This is the unique identifier of the shopper
        firstName:
          type: string
          description: This is the first name of the shopper
          example: John          
          maximum: 100
        lastName:
          type: string
          maximum: 100
          example: Doe
          description: This is the last name of the shopper
        dateOfBirth: 
          type: string
          minimum: 10
          maximum: 10
          format: date
          description: This is the date of birth of the shopper. Format [YYYY-MM-DD]
        email: 
          type: string
          maximum: 100
          format: email
          description: This is the email address of the shopper
          example: "john.doe@pxpfinancial.com"
    voucherResponse:
      required:
        - voucherNumber
        - state
        - stateMessage
        - amount
        - currency
        - paymentTypeAmounts
        - shopper
      properties:
        voucherNumber: 
            $ref: "#/components/schemas/voucherNumber"
            description: "This is the result of the Voucher Creation"
            example: "VoucherCreated"
        state: 
            type: string
            enum:
              - VoucherCreated
              - VoucherPaid
              - VoucherExpired
            example: "VoucherCreated"
        stateMessage:
          type: string
          example: "Voucher Created"
          description: "This is the result message of the Voucher Creation"          
        amount: 
          $ref: "#/components/schemas/amount"
        currency: 
          $ref: "#/components/schemas/currency"
        paymentTypeAmounts:
          $ref: "#/components/schemas/paymentTypeAmounts"                    
        shopper:
          $ref: "#/components/schemas/shopper"
    createVoucherResponse:
      required:
        - state
        - stateMessage
      properties:
        state:
          type: string
          example: "VoucherCreated"
          enum:
            - VoucherCreated
          description: "This is the result of the Voucher Creation"
        stateMessage:
          type: string
          example: "Voucher Created"
          description: "This is the result message of the Voucher Creation"
    transactionResponse:
      required:
        - systemTransactionId
        - state
        - stateMessage
      properties:
        systemTransactionId:
          type: string
          example: 1ed768bb-e88a-4636-91ae-67927ccbb02b                    
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          minimum: 36
          maximum: 36  
          description: This is the unique transaction id returned by Pxp Financial
        state:
          type: string
          example: "Approved"
          description: This is the result of the transaction
          enum:
            - Approved
        stateMessage:
          type: string
          example: "Approved"
          description: This is the result message of the transaction
    merchants:
      required:
        - id
        - name
        - merchantCategoryCode
        - address  
      properties:
          id: 
            type: string
            example: "MERC-0001"
            maximum: 20
            description: The unique merchant identifier, with which you want to process the transaction. This value is generated by PXP Financial
          name: 
            type: string  
            example: "Merchant Account 1"
            maximum: 100
            description: The merchant name, with which you want to process the transaction. This value is generated by PXP Financial
          merchantCategoryCode: 
            type: string  
            example: "5541"
            minimum: 4
            maximum: 4
            description: The merchant category code assigned to the merchant
          address: 
            $ref: "#/components/schemas/address"
            description: The address of the merchant
    address:
      required:
        - street
        - houseNoName
        - postalCode
        - city
        - state
        - country
      properties:
        street:
          type: string
          example: "Street Name"
          description: "The street name of the merchant"
          maximum: 100         
        houseNoName:
          type: string
          example: "House Name"
          description: "The house name or number of the merchant"
          maximum: 100  
        postalCode:
          type: string
          example: "Postal Code"
          description: "The postal code of the merchant"
          maximum: 15
        city:
          type: string
          example: "City"
          description: "The city of the merchant"
          maximum: 100  
        state:
          type: string
          example: "State"
          description: "The state of the merchant"
          maximum: 100
        country:
          type: string
          example: "GB"
          description: "The country of the merchant.  This is an ISO 3166-1 format"
          minimum: 2
          maximum: 2            
    currencies:
      required:
        - currencyCode
        - currencyNumber
        - currencyName
        - currencySymbol
      properties:
          currencyCode: 
            type: string
            example: "GBP"
            minimum: 3
            maximum: 3
            description: The ISO code of the currency
          currencyNumber: 
            type: integer  
            example: 826
            minimum: 3
            maximum: 3
            description: The ISO number of the currency
          currencyName: 
            type: string  
            example: "British Pound"
            description: The name of the currency
          currencySymbol: 
            type: string  
            example: "£"
            description: The symbol of the currency